package com.exjobb.backend.controller;

import com.exjobb.backend.dto.ContentRequest;
import com.exjobb.backend.service.AgentService;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/agent")
public class AgentController {

    private final AgentService agentService;

    public AgentController(AgentService agentService) {
        this.agentService = agentService;
    }


    /**
     * An endpoint to take a request and generate a content-plan
     * @param request A JSON-body that matches our ContentRequest-DTO.
     * @return A text string with the plan that was generated by the AI-agent.
     */
    @PostMapping("/generate-plan")
    public String generateContentPlan(@RequestBody ContentRequest request){
        return agentService.generateContentPlan(request);
    }
}
