package com.exjobb.backend.controller;

import com.exjobb.backend.dto.ContentRequest;
import com.exjobb.backend.entity.SocialMediaPost;
import com.exjobb.backend.entity.User;
import com.exjobb.backend.service.AgentService;
import com.exjobb.backend.service.UserService;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/agent")
public class AgentController {

    private final AgentService agentService;
    private final UserService userService;

    public AgentController(AgentService agentService, UserService userService) {
        this.agentService = agentService;
        this.userService = userService;
    }

    /**
     * An endpoint to take a request and generate a content-plan
     * @param request A JSON-body that matches our ContentRequest-DTO.
     * @return A SocialMediaPost object with the plan that was generated by the AI agent.
     */
    @PostMapping("/generate-plan")
    public SocialMediaPost generateContentPlan(@RequestBody ContentRequest request,
                                               Authentication authentication){
        // Get username from the authenticated jwt-token
        String username = authentication.getName();

        // Use userservice to get the user-object from the db
        User currentUser = userService.findByUsername(username)
                .orElseThrow(() -> new RuntimeException("User not found with username: " + username));

        // Send user object to agentservice
        return agentService.generateFullContent(request, currentUser);


        return agentService.generateFullContent(request);
    }
}
