spring.application.name=MarketingAgentFactoryV2

# Spring ai
spring.ai.vertex.ai.gemini.project-id=marketingagentfactoryv2
spring.ai.vertex.ai.gemini.location=europe-west1

# H2 Database Config
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=test
spring.datasource.password=test
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Actuator
management.endpoints.web.exposure.include=*

