import React, { useState } from 'react';
// IMPORTANT: Ensure 'ChatInterface.jsx' is located at 'src/components/ChatInterface.jsx'
import ChatInterface from './components/ChatInterface.jsx'; // Path: src/pages/ContentPage -> src/components
// IMPORTANT: Ensure 'PreviewPanel.jsx' is located at 'src/components/PreviewPanel.jsx'
import PreviewPanel from './components/PreviewPanel.jsx'; // Path: src/pages/ContentPage -> src/components

/**
 * ContentPage Component (AI Agent Interface)
 * Manages the top-level layout for the AI chat and content preview.
 */
function ContentPage() {
    // State to hold the content generated by the AI for the preview panel
    // This state is lifted up to ContentPage so both ChatInterface and PreviewPanel can interact with it.
    const [generatedContent, setGeneratedContent] = useState('');

    return (
        <div className="flex w-full h-[calc(100vh-64px)]">

            {/* Left Column: AI Chat Interface */}
            <div className="w-1/2 border-r border-gray-200 flex flex-col px-4 py-2">
                {/* ChatInterface component handles all chat logic and UI */}
                <ChatInterface onContentGenerated={setGeneratedContent} />
            </div>

            {/* Right Column: Content Preview */}
            <div className="w-1/2 flex flex-col bg-gray-100 p-4">
                {/* PreviewPanel displays the content generated by ChatInterface */}
                <PreviewPanel content={generatedContent} />
            </div>
        </div>
    );
}

export default ContentPage;
