spring.application.name=MarketingAgentFactoryV2

# Spring ai
spring.ai.vertex.ai.gemini.project-id=marketingagentfactoryv2
spring.ai.vertex.ai.gemini.location=europe-west1

# Database config
spring.datasource.url=jdbc:mysql://34.51.207.16:3306/MarketingAgentFactoryV2
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# Actuator
management.endpoints.web.exposure.include=*

# JWT Configuration
jwt.secret=mySecretKey1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
jwt.expiration=3600000

# application.properties
facebook.app.id=1079742340803503
facebook.app.secret=7101ab8a8922562eaa8f19a7b2d857f2
facebook.redirect.uri=http://localhost:8080/api/auth/facebook/callback

twitter.client.id=WU9PbXhjVE5JY21uczY1YmZxdUw6MTpjaQ
twitter.client.secret=pxU5Su3gfW7Dq9OBmRjhRcgiBSP4ef6r-37yZaM995ixlKMnrf
twitter.redirect.uri=http://localhost:8080/api/auth/twitter/callback
twitter.oauth.token-url=https://api.x.com/2/oauth2/token
twitter.api.users-me-url=https://api.x.com/2/users/me
twitter.api.tweets-url=https://api.x.com/2/tweets

# API key for Newsdata.io
news.api.key=pub_a2ac9b78d50b4de998693209f4e3b229